spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:5051/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:5052/
          predicates:
            - Path=/products/**
